name: CI for Docker Image

# This workflow triggers on every push to the main branch or a pull request.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (set your Docker Hub credentials in GitHub secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      # Step 5: Run Tests (optional step, based on what testing tools you use)
      # Assuming your Docker container has tests to run after the image is built
      - name: Run Tests
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} npm test

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
