name: CI for Docker Image

# This workflow triggers on every push to the main branch or a pull request.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "midothijsen" | docker login --username midothijsen --password VmnMediaTest123


      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build . -t midothijsen/my-app:${{ github.sha }}


      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push midothijsen/my-app:${{ github.sha }}
